chore: update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   push:
     branches:
-      - master
+      - agent-master
     paths:
       - "**/*.go"
       - "go.mod"
@@ -24,15 +24,13 @@ jobs:
   build:
     strategy:
       matrix:
-        # Include amd64 on all platforms.
         goos: [linux]
-        goarch: [amd64,  arm64]
+        goarch: [amd64, arm64]
       fail-fast: false
     runs-on: ubuntu-latest
     env:
       GOOS: ${{ matrix.goos }}
       GOARCH: ${{ matrix.goarch }}
-      GOARM: ${{ matrix.goarm }}
       CGO_ENABLED: 0
     steps:
       - name: Checkout codebase
@@ -40,30 +38,34 @@ jobs:
       - name: Show workflow information
         id: get_filename
         run: |
-          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOMIPS\"].friendlyName" -r < .github/build/friendly-filenames.json)
-          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
-          echo "::set-output name=ASSET_NAME::$_NAME"
+          export _NAME=$(jq ".[\"$GOOS-$GOARCH\"].friendlyName" -r < .github/build/friendly-filenames.json)
+          echo "_NAME: $_NAME"
+          [ -z "$_NAME" ] && echo "Error: _NAME is empty" && exit 1
+          echo "GOOS: $GOOS, GOARCH: $GOARCH, RELEASE_NAME: $_NAME"
           echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV
-
+      - name: Debug output
+        run: |
+          echo "ASSET_NAME from environment: $ASSET_NAME"
       - name: Set up Go
         uses: actions/setup-go@v2
         with:
-          go-version: 1.21.4
+          go-version: '1.21.4'
       - name: Get project dependencies
         run: go mod download
+
       - name: Build Server
         run: |
           mkdir -p build_assets
-          go build -v -o build_assets/server-anytls -trimpath -ldflags "-s -w" ./cmd/server
+          go build -v -o build_assets/server-anytls-agent -trimpath -ldflags "-s -w" ./cmd/server-agent
       - name: Build Mips softfloat Server
         if: matrix.goarch == 'mips' || matrix.goarch == 'mipsle'
         run: |
-            GOMIPS=softfloat go build -v -o build_assets/server-anytls-softfloat -trimpath -ldflags "-s -w" ./cmd/server
+            GOMIPS=softfloat go build -v -o build_assets/server-anytls-agent-softfloat -trimpath -ldflags "-s -w" ./cmd/server-agent
       - name: Rename Windows Server
         if: matrix.goos == 'windows'
         run: |
           cd ./build_assets || exit 1
-          mv server-anytls server-anytls.exe
+          mv server-anytls-agent server-anytls-agent.exe
       - name: Prepare to release
         run: |
           cp ${GITHUB_WORKSPACE}/README.md ./build_assets/README.md
@@ -73,9 +75,9 @@ jobs:
         run: |
           pushd build_assets || exit 1
           touch -mt $(date +%Y01010000) *
-          zip -9vr ../server-anytls-$ASSET_NAME.zip .
+          zip -9vr ../server-anytls-agent-$ASSET_NAME.zip .
           popd || exit 1
-          FILE=./server-anytls-$ASSET_NAME.zip
+          FILE=./server-anytls-agent-$ASSET_NAME.zip
           DGST=$FILE.dgst
           for METHOD in {"md5","sha1","sha256","sha512"}
           do
@@ -83,18 +85,21 @@ jobs:
           done
       - name: Change the name
         run: |
-          mv build_assets server-anytls-$ASSET_NAME
+          mv build_assets server-anytls-agent-$ASSET_NAME
+      # Upload to artifacts
+
       - name: Upload files to Artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: server-anytls-${{ steps.get_filename.outputs.ASSET_NAME }}
+          name: server-anytls-agent-${{ env.ASSET_NAME }}
           path: |
-            ./server-anytls-${{ steps.get_filename.outputs.ASSET_NAME }}/*
+            ./server-anytls-agent-${{ env.ASSET_NAME }}
+      # Upload binaries to release
       - name: Upload binaries to release
         uses: svenstaro/upload-release-action@v2
         if: github.event_name == 'release'
         with:
-          repo_token: ${{secrets.GITHUB_TOKEN}}
-          file: ./server-anytls-${{ steps.get_filename.outputs.ASSET_NAME }}.zip*
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: ./server-anytls-agent-${{ env.ASSET_NAME }}.zip*
           tag: ${{ github.ref }}
           file_glob: true
